// Auto-generated from frontend data.ts
export const cities = [
  {
    id: "chennai",
    name: "Chennai",
    tagline: "Where heritage meets the coast",
    description: "A vibrant coastal metropolis blending ancient Dravidian temples with modern culture, long sandy beaches, and legendary South Indian cuisine.",
    personality: "coastal heritage",
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: "coimbatore",
    name: "Coimbatore",
    tagline: "Gateway to the Western Ghats",
    description: "A thriving city nestled at the foothills of the Nilgiris, known for its pleasant climate, textile industry, and proximity to stunning hill stations.",
    personality: "industrial charm",
    lat: 11.0168,
    lng: 76.9558,
  },
  {
    id: "madurai",
    name: "Madurai",
    tagline: "The temple city that never sleeps",
    description: "One of the oldest continuously inhabited cities in the world, Madurai pulses with the energy of the magnificent Meenakshi Temple and its centuries-old bazaars.",
    personality: "ancient grandeur",
    lat: 9.9252,
    lng: 78.1198,
  },
  {
    id: "ooty",
    name: "Ooty",
    tagline: "Queen of the Nilgiris",
    description: "A serene hill station draped in tea plantations and misty peaks, offering cool retreats, botanical gardens, and winding mountain railways.",
    personality: "misty hills",
    lat: 11.4102,
    lng: 76.6950,
  },
];

export const places = [
  // ===== CHENNAI =====
  {
    id: "marina-beach",
    name: "Marina Beach",
    city: "chennai",
    type: "beach",
    description: "One of the longest urban beaches in the world, stretching 13 km along the Bay of Bengal.",
    tags: ["beach", "sunset", "iconic"],
    lat: 13.0500, lng: 80.2824,
    popularity: 0.95, baseCrowd: 0.7,
    peakHours: [17, 18, 19],
    bestTime: "Early morning or sunset",
    culturalInfo: {
      myth: "Legend says the beach was a gift from the sea god to the Pallava kings.",
      festival: "During Pongal, thousands gather here for beach celebrations and kolam competitions.",
      history: "Built along the shore during British colonial rule, it became India's pride as the second-longest beach globally.",
    },
  },
  {
    id: "kapaleeshwarar-temple",
    name: "Kapaleeshwarar Temple",
    city: "chennai",
    type: "temple",
    description: "A stunning 7th-century Dravidian temple dedicated to Lord Shiva, located in Mylapore.",
    tags: ["temple", "heritage", "architecture"],
    lat: 13.0339, lng: 80.2695,
    popularity: 0.9, baseCrowd: 0.6,
    peakHours: [9, 10, 17, 18],
    bestTime: "Early morning for peaceful darshan",
    culturalInfo: {
      myth: "Shiva is said to have restored Parvati's peacock form here, hence the name 'Kapaleeshwarar.'",
      festival: "The Arubathimoovar festival sees 63 Nayanar saints' bronze idols paraded through Mylapore streets.",
      history: "Originally built by the Pallavas in the 7th century, it was reconstructed by the Vijayanagara rulers in the 16th century.",
    },
  },
  {
    id: "fort-st-george",
    name: "Fort St. George",
    city: "chennai",
    type: "museum",
    description: "The first English fortress in India, now housing a museum with colonial-era artifacts.",
    tags: ["museum", "history", "colonial"],
    lat: 13.0798, lng: 80.2870,
    popularity: 0.7, baseCrowd: 0.3,
    peakHours: [10, 11, 14, 15],
    bestTime: "Weekday mornings",
    culturalInfo: {
      myth: "Locals believe tunnels connect the fort to distant parts of the city, though none have been found.",
      festival: "Republic Day and Independence Day celebrations are held here with military parades.",
      history: "Founded in 1644 by the British East India Company, it became the nucleus of modern Chennai.",
    },
  },
  {
    id: "san-thome-basilica",
    name: "San Thome Basilica",
    city: "chennai",
    type: "church",
    description: "A Gothic-style Catholic church built over the tomb of St. Thomas the Apostle.",
    tags: ["church", "heritage", "gothic"],
    lat: 13.0334, lng: 80.2778,
    popularity: 0.75, baseCrowd: 0.35,
    peakHours: [9, 10, 16, 17],
    bestTime: "Morning for quiet reflection",
    culturalInfo: {
      myth: "St. Thomas is believed to have arrived in India in 52 AD and was martyred on St. Thomas Mount.",
      festival: "The annual feast of St. Thomas on July 3rd draws thousands of pilgrims.",
      history: "Originally built by the Portuguese in the 16th century, rebuilt by the British in 1893 in neo-Gothic style.",
    },
  },
  {
    id: "dakshinachitra",
    name: "DakshinaChitra",
    city: "chennai",
    type: "museum",
    description: "A living museum showcasing the art, architecture, and crafts of South India.",
    tags: ["museum", "culture", "crafts"],
    lat: 12.7945, lng: 80.2310,
    popularity: 0.65, baseCrowd: 0.25,
    peakHours: [10, 11, 15, 16],
    bestTime: "Weekday mornings",
    culturalInfo: {
      myth: "Each reconstructed house carries the spirit and stories of its original owners.",
      festival: "Annual craft melas feature artisans from across South India demonstrating traditional techniques.",
      history: "Established in 1996 by the Madras Craft Foundation to preserve vanishing architectural heritage.",
    },
  },
  {
    id: "elliot-beach",
    name: "Elliot's Beach",
    city: "chennai",
    type: "beach",
    description: "A quieter, cleaner beach south of Marina, popular with families and joggers.",
    tags: ["beach", "peaceful", "family"],
    lat: 13.0004, lng: 80.2725,
    popularity: 0.7, baseCrowd: 0.4,
    peakHours: [17, 18, 19],
    bestTime: "Early morning or late evening",
    culturalInfo: {
      myth: "Named after Edward Elliot, the Chief Magistrate of Madras, whose bungalow stood nearby.",
      festival: "Weekend food festivals and kite-flying events draw locals throughout the year.",
      history: "Developed in the late 19th century as a residential beach for the British colonial elite.",
    },
  },
  {
    id: "government-museum-chennai",
    name: "Government Museum",
    city: "chennai",
    type: "museum",
    description: "The second oldest museum in India with a remarkable collection of Roman antiquities and bronze sculptures.",
    tags: ["museum", "art", "history"],
    lat: 13.0674, lng: 80.2568,
    popularity: 0.6, baseCrowd: 0.25,
    peakHours: [10, 11, 14, 15],
    bestTime: "Weekday mornings",
    culturalInfo: {
      myth: "A bronze Nataraja statue is said to vibrate with cosmic energy during Mahashivratri.",
      festival: "Special exhibitions during Tamil Heritage Month draw school groups and historians.",
      history: "Founded in 1851, it houses the world's largest collection of Roman antiquities found in India.",
    },
  },
  {
    id: "thiruvanmiyur-beach",
    name: "Thiruvanmiyur Beach",
    city: "chennai",
    type: "beach",
    description: "A serene stretch of coastline popular with morning walkers and surfers.",
    tags: ["beach", "surfing", "quiet"],
    lat: 12.9830, lng: 80.2630,
    popularity: 0.5, baseCrowd: 0.2,
    peakHours: [6, 7, 17, 18],
    bestTime: "Early morning for surfing",
    culturalInfo: {
      myth: "Fishermen believe the ocean here is watched over by the goddess at Thiruvanmiyur temple.",
      festival: "Local fishing community holds sea worship during Aadi month.",
      history: "Named after the ancient Marundeeswarar Temple nearby, the area has been inhabited since the Pallava period.",
    },
  },
  {
    id: "valluvar-kottam",
    name: "Valluvar Kottam",
    city: "chennai",
    type: "museum",
    description: "A monument dedicated to the Tamil poet-saint Thiruvalluvar, shaped like a temple chariot.",
    tags: ["monument", "heritage", "literature"],
    lat: 13.0520, lng: 80.2410,
    popularity: 0.55, baseCrowd: 0.2,
    peakHours: [10, 11, 16, 17],
    bestTime: "Evening for the lit-up monument",
    culturalInfo: {
      myth: "All 1,330 Thirukkural couplets are inscribed in granite — reading them all is said to bring wisdom.",
      festival: "Thiruvalluvar Day on January 15th sees poets and scholars gathering for literary events.",
      history: "Inaugurated in 1976, the auditorium held the Guinness Record for largest in Asia at the time.",
    },
  },
  {
    id: "guindy-national-park",
    name: "Guindy National Park",
    city: "chennai",
    type: "park",
    description: "One of the smallest national parks in India, right in the heart of the city with blackbucks and spotted deer.",
    tags: ["wildlife", "park", "nature"],
    lat: 13.0063, lng: 80.2376,
    popularity: 0.6, baseCrowd: 0.3,
    peakHours: [9, 10, 15, 16],
    bestTime: "Early morning for wildlife spotting",
    culturalInfo: {
      myth: "The park's blackbucks are considered sacred, believed to be descendants of celestial deer.",
      festival: "Wildlife Week in October features nature walks and conservation workshops.",
      history: "Originally the private hunting grounds of the Governor of Madras, declared a national park in 1977.",
    },
  },

  // ===== COIMBATORE =====
  {
    id: "marudhamalai-temple",
    name: "Marudhamalai Temple",
    city: "coimbatore",
    type: "temple",
    description: "A hilltop temple dedicated to Lord Murugan, offering panoramic views of Coimbatore.",
    tags: ["temple", "hilltop", "spiritual"],
    lat: 11.0459, lng: 76.8871,
    popularity: 0.85, baseCrowd: 0.5,
    peakHours: [8, 9, 17, 18],
    bestTime: "Early morning for sunrise views",
    culturalInfo: {
      myth: "Lord Murugan is said to have meditated here, and the herbs on the hill have healing properties.",
      festival: "Thaipusam celebrations see devotees carrying kavadi in a procession up the hill.",
      history: "The temple dates back to the Chera dynasty period, making it over 1,200 years old.",
    },
  },
  {
    id: "dhyanalinga",
    name: "Dhyanalinga Temple",
    city: "coimbatore",
    type: "temple",
    description: "A unique yogic temple consecrated by Sadhguru, featuring a powerful meditation space.",
    tags: ["meditation", "spiritual", "modern"],
    lat: 11.0439, lng: 76.8396,
    popularity: 0.8, baseCrowd: 0.4,
    peakHours: [10, 11, 15, 16],
    bestTime: "Weekday mornings for silent meditation",
    culturalInfo: {
      myth: "The lingam is said to radiate all seven chakra energies, a feat of yogic science.",
      festival: "Mahashivratri at Isha Foundation draws millions for an all-night meditation event.",
      history: "Consecrated in 1999 by Sadhguru Jaggi Vasudev after three lifetimes of yogic preparation.",
    },
  },
  {
    id: "voc-park",
    name: "VOC Park & Zoo",
    city: "coimbatore",
    type: "park",
    description: "A sprawling park with a zoo, aquarium, and amusement rides in the heart of Coimbatore.",
    tags: ["park", "zoo", "family"],
    lat: 11.0110, lng: 76.9620,
    popularity: 0.7, baseCrowd: 0.5,
    peakHours: [10, 11, 15, 16],
    bestTime: "Weekday mornings",
    culturalInfo: {
      myth: "Named after freedom fighter V.O. Chidambaram Pillai, the park symbolizes Coimbatore's pride.",
      festival: "Children's Day celebrations bring special events and shows to the zoo.",
      history: "Established in 1925, it's one of the oldest parks in Tamil Nadu.",
    },
  },
  {
    id: "kovai-kutralam",
    name: "Kovai Kutralam Falls",
    city: "coimbatore",
    type: "waterfall",
    description: "A seasonal waterfall nestled in the Siruvani hills, nicknamed 'Coimbatore's own Courtallam.'",
    tags: ["waterfall", "nature", "trekking"],
    lat: 10.9340, lng: 76.7310,
    popularity: 0.75, baseCrowd: 0.6,
    peakHours: [10, 11, 14, 15],
    bestTime: "Monsoon season (July–September)",
    culturalInfo: {
      myth: "The waters are believed to have medicinal properties from the herbs in the surrounding hills.",
      festival: "During monsoon, locals celebrate the first rains with picnics and community gatherings.",
      history: "A natural formation in the Western Ghats, it's been a pilgrimage for nature lovers for centuries.",
    },
  },
  {
    id: "brookefields-mall",
    name: "Brookefields Mall",
    city: "coimbatore",
    type: "market",
    description: "Coimbatore's largest shopping and entertainment destination with international brands.",
    tags: ["shopping", "entertainment", "modern"],
    lat: 11.0200, lng: 76.9680,
    popularity: 0.65, baseCrowd: 0.55,
    peakHours: [14, 15, 18, 19, 20],
    bestTime: "Weekday afternoons",
    culturalInfo: {
      myth: "Built on land that was once a cotton trading hub, reflecting Coimbatore's textile heritage.",
      festival: "Diwali and Christmas shopping festivals with special offers and cultural performances.",
      history: "Opened in 2010, it marked Coimbatore's transformation into a modern retail destination.",
    },
  },
  {
    id: "siruvani-dam",
    name: "Siruvani Dam",
    city: "coimbatore",
    type: "lake",
    description: "Home to what's considered the second tastiest water in the world, surrounded by pristine forests.",
    tags: ["nature", "dam", "scenic"],
    lat: 10.9490, lng: 76.7280,
    popularity: 0.7, baseCrowd: 0.2,
    peakHours: [9, 10, 11],
    bestTime: "October–February for best weather",
    culturalInfo: {
      myth: "Local tribes believe the dam's water is blessed by forest spirits.",
      festival: "Tribal communities hold harvest festivals near the dam with traditional dances.",
      history: "Built in 1966, it supplies most of Coimbatore's drinking water from the Western Ghats.",
    },
  },
  {
    id: "perur-pateeswarar-temple",
    name: "Perur Pateeswarar Temple",
    city: "coimbatore",
    type: "temple",
    description: "An ancient Shiva temple known for its exquisite Nataraja sculpture and musical pillars.",
    tags: ["temple", "ancient", "sculpture"],
    lat: 11.0030, lng: 76.9070,
    popularity: 0.6, baseCrowd: 0.3,
    peakHours: [8, 9, 17, 18],
    bestTime: "Morning puja time",
    culturalInfo: {
      myth: "Shiva is believed to have performed the cosmic dance here, and the musical pillars replay the rhythm.",
      festival: "Navarathri festival features nine nights of classical dance at the temple mandapam.",
      history: "Built by the Chera kings over 1,500 years ago, it's one of the oldest Shiva temples in the Kongu region.",
    },
  },
  {
    id: "vellingiri-hills",
    name: "Vellingiri Hills",
    city: "coimbatore",
    type: "hill",
    description: "Known as the 'Kailash of the South,' this sacred hill has a Shiva temple at the summit.",
    tags: ["trekking", "spiritual", "nature"],
    lat: 11.0100, lng: 76.7600,
    popularity: 0.7, baseCrowd: 0.3,
    peakHours: [5, 6, 7],
    bestTime: "Amavasya (new moon) trekking nights",
    culturalInfo: {
      myth: "Seven hills represent seven chakras — trekking all seven cleanses your spiritual energy.",
      festival: "Thousands trek on Amavasya nights, carrying ghee lamps to the summit temple.",
      history: "The Siddhas (ancient mystics) are said to have meditated here for thousands of years.",
    },
  },
  {
    id: "gedee-car-museum",
    name: "GeDee Car Museum",
    city: "coimbatore",
    type: "museum",
    description: "A unique museum with vintage and classic cars, including a Rolls Royce and Cadillac collection.",
    tags: ["museum", "cars", "vintage"],
    lat: 11.0230, lng: 76.9550,
    popularity: 0.5, baseCrowd: 0.2,
    peakHours: [10, 11, 15, 16],
    bestTime: "Weekday mornings",
    culturalInfo: {
      myth: "The Rolls Royce Silver Ghost is said to start on its own during full moon nights.",
      festival: "Vintage car rallies are organized during the Coimbatore Auto Expo.",
      history: "Founded by GD Naidu's family trust, celebrating Coimbatore's nickname 'Detroit of India.'",
    },
  },
  {
    id: "black-thunder",
    name: "Black Thunder Water Park",
    city: "coimbatore",
    type: "park",
    description: "Asia's largest water theme park located at Mettupalayam, a perfect family getaway.",
    tags: ["waterpark", "family", "adventure"],
    lat: 11.2900, lng: 76.9400,
    popularity: 0.8, baseCrowd: 0.6,
    peakHours: [11, 12, 14, 15],
    bestTime: "Weekdays to avoid queues",
    culturalInfo: {
      myth: "Built amidst the foothills, locals say the water is naturally cool from underground springs.",
      festival: "Summer carnival with special rides and DJ nights during April–May.",
      history: "Opened in 1994, it pioneered the water park culture in South India.",
    },
  },

  // ===== MADURAI =====
  {
    id: "meenakshi-temple",
    name: "Meenakshi Amman Temple",
    city: "madurai",
    type: "temple",
    description: "One of India's most magnificent temples with 14 towering gopurams covered in thousands of colorful sculptures.",
    tags: ["temple", "iconic", "architecture"],
    lat: 9.9195, lng: 78.1193,
    popularity: 1.0, baseCrowd: 0.8,
    peakHours: [9, 10, 11, 17, 18, 19],
    bestTime: "5:30 AM for opening ceremony",
    culturalInfo: {
      myth: "Built where Shiva married Meenakshi, the fish-eyed goddess — the divine wedding is reenacted every night.",
      festival: "Chithirai Thiruvizha, the 10-day celestial wedding festival, draws over a million devotees.",
      history: "Originally built by Kulasekara Pandya in the 6th century BC, expanded massively by the Nayak dynasty in the 16th century.",
    },
  },
  {
    id: "thirumalai-nayak-palace",
    name: "Thirumalai Nayak Palace",
    city: "madurai",
    type: "museum",
    description: "A 17th-century Indo-Saracenic palace with massive pillars and a grand courtyard.",
    tags: ["palace", "heritage", "architecture"],
    lat: 9.9165, lng: 78.1226,
    popularity: 0.8, baseCrowd: 0.4,
    peakHours: [10, 11, 15, 16],
    bestTime: "Evening for the sound and light show",
    culturalInfo: {
      myth: "The palace is said to have been four times its current size, with the rest demolished by a grandson.",
      festival: "Annual Navaratri celebrations feature classical dance performances in the palace courtyard.",
      history: "Built in 1636 by King Thirumalai Nayak, combining Italian and Dravidian architectural styles.",
    },
  },
  {
    id: "gandhi-museum-madurai",
    name: "Gandhi Memorial Museum",
    city: "madurai",
    type: "museum",
    description: "Houses the bloodstained dhoti Mahatma Gandhi wore when he was assassinated.",
    tags: ["museum", "history", "freedom"],
    lat: 9.9270, lng: 78.1140,
    popularity: 0.65, baseCrowd: 0.2,
    peakHours: [10, 11, 14, 15],
    bestTime: "Morning on weekdays",
    culturalInfo: {
      myth: "Visitors say they feel a powerful spiritual presence near the dhoti exhibit.",
      festival: "Gandhi Jayanti (October 2) features special exhibitions and prayer meetings.",
      history: "Established in 1959 in the old Tamukkam Palace, it chronicles India's freedom struggle.",
    },
  },
  {
    id: "pudhu-mandapam",
    name: "Pudhu Mandapam",
    city: "madurai",
    type: "market",
    description: "A 17th-century pillared hall now bustling with tailors and textile shops.",
    tags: ["market", "heritage", "shopping"],
    lat: 9.9200, lng: 78.1188,
    popularity: 0.7, baseCrowd: 0.6,
    peakHours: [10, 11, 16, 17, 18],
    bestTime: "Morning for best bargaining",
    culturalInfo: {
      myth: "Each pillar tells a story from the epics — find the pillar of your birth star for good luck.",
      festival: "During temple festivals, the mandapam transforms into a cultural performance space.",
      history: "Built by Thirumalai Nayak in the 17th century as a wedding gift to the goddess Meenakshi.",
    },
  },
  {
    id: "alagar-kovil",
    name: "Alagar Kovil",
    city: "madurai",
    type: "temple",
    description: "A Vishnu temple in a scenic hill setting, surrounded by natural springs and caves.",
    tags: ["temple", "nature", "scenic"],
    lat: 10.0560, lng: 78.2200,
    popularity: 0.6, baseCrowd: 0.3,
    peakHours: [9, 10, 16, 17],
    bestTime: "Morning for trekking and darshan",
    culturalInfo: {
      myth: "Lord Vishnu is said to have appeared here as Alagar to attend his sister Meenakshi's wedding.",
      festival: "During Chithirai, Lord Alagar's procession from here to Madurai is the festival's highlight.",
      history: "Dates back to the Pandya dynasty, carved into the Alagar Hills with rock-cut shrines.",
    },
  },
  {
    id: "vaigai-dam",
    name: "Vaigai Dam",
    city: "madurai",
    type: "lake",
    description: "A scenic dam across the Vaigai river, offering boating and hillside picnic spots.",
    tags: ["dam", "nature", "picnic"],
    lat: 10.0470, lng: 77.5760,
    popularity: 0.55, baseCrowd: 0.3,
    peakHours: [10, 11, 15, 16],
    bestTime: "October–January for full water levels",
    culturalInfo: {
      myth: "The Vaigai river is considered sacred, believed to purify sins of those who bathe in it.",
      festival: "Jallikattu celebrations along the Vaigai river draw massive crowds during Pongal.",
      history: "The modern dam was built in 1959, but the Vaigai has been Madurai's lifeline for over 2,500 years.",
    },
  },
  {
    id: "koodal-azhagar-temple",
    name: "Koodal Azhagar Temple",
    city: "madurai",
    type: "temple",
    description: "A rare Vishnu temple where the deity appears in standing, sitting, and reclining postures on three levels.",
    tags: ["temple", "unique", "spiritual"],
    lat: 9.9210, lng: 78.1170,
    popularity: 0.55, baseCrowd: 0.25,
    peakHours: [8, 9, 17, 18],
    bestTime: "Morning for quiet darshan",
    culturalInfo: {
      myth: "The three forms of Vishnu here represent creation, preservation, and cosmic rest.",
      festival: "Vaikunta Ekadasi draws long queues as devotees believe heaven's gates open on this day.",
      history: "One of the 108 Divya Desams, this ancient temple was praised by the Alwar saints over 1,000 years ago.",
    },
  },
  {
    id: "samanar-hills",
    name: "Samanar Hills (Jain Caves)",
    city: "madurai",
    type: "hill",
    description: "Ancient Jain rock-cut caves with inscriptions dating back to the 1st century BC.",
    tags: ["caves", "jain", "ancient", "trekking"],
    lat: 9.8940, lng: 78.0450,
    popularity: 0.45, baseCrowd: 0.15,
    peakHours: [7, 8, 9],
    bestTime: "Early morning to avoid heat",
    culturalInfo: {
      myth: "Jain monks are said to have attained enlightenment in these caves through extreme austerity.",
      festival: "Mahavir Jayanti sees the Jain community performing special pujas at the cave shrines.",
      history: "Contains Tamil Brahmi inscriptions from the 2nd century BC, proving Madurai's ancient Jain heritage.",
    },
  },
  {
    id: "meghamalai",
    name: "Meghamalai (Cloud Mountain)",
    city: "madurai",
    type: "hill",
    description: "A hidden gem above the clouds with pristine forests, coffee estates, and endangered wildlife.",
    tags: ["hill", "wildlife", "offbeat"],
    lat: 9.6900, lng: 77.4200,
    popularity: 0.4, baseCrowd: 0.1,
    peakHours: [9, 10],
    bestTime: "November–March for clear skies",
    culturalInfo: {
      myth: "Tribal folklore says the mountain touches the clouds because it's where gods rest.",
      festival: "Tribal harvest festival 'Pongal Vizha' is celebrated with traditional music and dance.",
      history: "Long hidden from tourists due to tea estate restrictions, it was opened to the public only in 2013.",
    },
  },
  {
    id: "banana-market-madurai",
    name: "Mattuthavani Banana Market",
    city: "madurai",
    type: "market",
    description: "Asia's largest banana market where over 15 varieties of bananas are traded daily.",
    tags: ["market", "unique", "local"],
    lat: 9.9350, lng: 78.1400,
    popularity: 0.5, baseCrowd: 0.6,
    peakHours: [5, 6, 7, 8],
    bestTime: "5 AM for the auction spectacle",
    culturalInfo: {
      myth: "Traders say offering the first bunch to Lord Ganesha ensures a profitable day.",
      festival: "During Pongal, special banana varieties are auctioned for temple offerings.",
      history: "Operating for over 200 years, it moves over 1 lakh bunches of bananas daily.",
    },
  },

  // ===== OOTY =====
  {
    id: "botanical-garden",
    name: "Government Botanical Garden",
    city: "ooty",
    type: "park",
    description: "A 55-acre garden with over 650 species of plants, including a 20-million-year-old fossil tree.",
    tags: ["garden", "nature", "heritage"],
    lat: 11.4143, lng: 76.7072,
    popularity: 0.9, baseCrowd: 0.6,
    peakHours: [10, 11, 14, 15],
    bestTime: "May during the flower show",
    culturalInfo: {
      myth: "The fossilized tree is said to hold the memory of ancient Nilgiri forests.",
      festival: "The annual Flower Show in May attracts over 2 lakh visitors with stunning floral displays.",
      history: "Established in 1848 by the Marquis of Tweeddale, it's one of India's finest botanical collections.",
    },
  },
  {
    id: "ooty-lake",
    name: "Ooty Lake",
    city: "ooty",
    type: "lake",
    description: "An artificial lake surrounded by eucalyptus trees, offering boating with misty mountain views.",
    tags: ["lake", "boating", "scenic"],
    lat: 11.4036, lng: 76.6886,
    popularity: 0.85, baseCrowd: 0.55,
    peakHours: [10, 11, 14, 15, 16],
    bestTime: "Early morning for misty views",
    culturalInfo: {
      myth: "Toda tribespeople believe the lake was created by the tears of a Toda princess longing for her homeland.",
      festival: "The annual boat race in May draws teams from across Tamil Nadu.",
      history: "Created by John Sullivan in 1824 by damming a stream, originally used for fishing and irrigation.",
    },
  },
  {
    id: "doddabetta-peak",
    name: "Doddabetta Peak",
    city: "ooty",
    type: "hill",
    description: "The highest peak in the Nilgiri mountains at 2,637m, with a telescope house and panoramic views.",
    tags: ["peak", "viewpoint", "trekking"],
    lat: 11.4000, lng: 76.7350,
    popularity: 0.88, baseCrowd: 0.5,
    peakHours: [9, 10, 11, 14, 15],
    bestTime: "Clear mornings for best visibility",
    culturalInfo: {
      myth: "Toda tribes consider this peak sacred, a dwelling place of their ancestors' spirits.",
      festival: "Sunrise trekking events on New Year's Day have become a popular tradition.",
      history: "The name means 'big peak' in Badaga language. A telescope house was installed in the 1990s for tourists.",
    },
  },
  {
    id: "nilgiri-mountain-railway",
    name: "Nilgiri Mountain Railway",
    city: "ooty",
    type: "museum",
    description: "A UNESCO World Heritage toy train winding through 16 tunnels and over 250 bridges.",
    tags: ["railway", "heritage", "UNESCO"],
    lat: 11.4000, lng: 76.6950,
    popularity: 0.92, baseCrowd: 0.7,
    peakHours: [8, 9, 10],
    bestTime: "First train for misty mountain magic",
    culturalInfo: {
      myth: "Engineers say the track has a spirit of its own — it knows when to slow down in fog.",
      festival: "Heritage railway celebrations on its anniversary feature vintage steam engines.",
      history: "Built by the British in 1908, it's one of the steepest rack railways in the world, using the only rack and pinion system in India.",
    },
  },
  {
    id: "tea-museum",
    name: "Tea Museum",
    city: "ooty",
    type: "museum",
    description: "A museum showcasing the history and process of tea-making in the Nilgiris.",
    tags: ["museum", "tea", "culture"],
    lat: 11.3910, lng: 76.7560,
    popularity: 0.65, baseCrowd: 0.3,
    peakHours: [10, 11, 14, 15],
    bestTime: "Morning for factory tour",
    culturalInfo: {
      myth: "Legend has it that the first tea seeds were smuggled from China in a diplomat's suitcase.",
      festival: "Tea festivals in December celebrate the Nilgiri flush with tastings and plantation tours.",
      history: "Tea cultivation began here in 1835, making the Nilgiris one of the oldest tea regions in India.",
    },
  },
  {
    id: "pykara-falls",
    name: "Pykara Falls & Lake",
    city: "ooty",
    type: "waterfall",
    description: "A stunning waterfall and lake surrounded by shola forests, sacred to the Toda tribe.",
    tags: ["waterfall", "lake", "tribal"],
    lat: 11.4620, lng: 76.6040,
    popularity: 0.7, baseCrowd: 0.35,
    peakHours: [10, 11, 14, 15],
    bestTime: "Monsoon for full flow",
    culturalInfo: {
      myth: "The Toda tribe considers Pykara sacred — they believe spirits of ancestors reside in the waters.",
      festival: "Toda tribal ceremonies are held near the river during the harvest season.",
      history: "A hydroelectric project was established here in 1932, one of the earliest in South India.",
    },
  },
  {
    id: "rose-garden-ooty",
    name: "Rose Garden",
    city: "ooty",
    type: "park",
    description: "A terraced garden with over 20,000 varieties of roses spread across 10 acres on a hillside.",
    tags: ["garden", "roses", "photography"],
    lat: 11.4150, lng: 76.7120,
    popularity: 0.75, baseCrowd: 0.45,
    peakHours: [10, 11, 14, 15],
    bestTime: "May–June for peak blooms",
    culturalInfo: {
      myth: "Local legend says a Toda chief planted the first rose here for his beloved.",
      festival: "Rose and Flower Show in May showcases exotic hybrid varieties from across India.",
      history: "Established in 1995 by the Tamil Nadu Horticulture Department, it won a Garden of Excellence award.",
    },
  },
  {
    id: "avalanche-lake",
    name: "Avalanche Lake",
    city: "ooty",
    type: "lake",
    description: "A pristine lake formed by a massive landslide in 1823, surrounded by dense shola forests.",
    tags: ["lake", "trekking", "fishing"],
    lat: 11.3900, lng: 76.5800,
    popularity: 0.6, baseCrowd: 0.15,
    peakHours: [9, 10, 11],
    bestTime: "October–March for clear weather",
    culturalInfo: {
      myth: "Tribals believe the landslide was caused by a deity stamping its foot in anger.",
      festival: "Annual trout fishing season opens in April, drawing anglers from across the country.",
      history: "Named after the 1823 landslide, it became a favourite retreat of British officers for trout fishing.",
    },
  },
  {
    id: "toda-hamlet",
    name: "Toda Tribal Village",
    city: "ooty",
    type: "museum",
    description: "A living heritage site showcasing the unique barrel-shaped houses and culture of the Toda tribe.",
    tags: ["tribal", "heritage", "culture"],
    lat: 11.4050, lng: 76.6900,
    popularity: 0.45, baseCrowd: 0.1,
    peakHours: [9, 10, 11],
    bestTime: "Morning with a local guide",
    culturalInfo: {
      myth: "The Toda believe they and their buffaloes were created together by the goddess Teikirshy.",
      festival: "Annual Toda New Year ('Modh') features dairy rituals and the sacred buffalo dance.",
      history: "The Toda are one of the oldest surviving tribal communities, with roots going back over 2,000 years in the Nilgiris.",
    },
  },
  {
    id: "pine-forest-ooty",
    name: "Pine Forest",
    city: "ooty",
    type: "park",
    description: "Rows of towering pine trees creating a magical forest canopy — a Bollywood favourite filming spot.",
    tags: ["forest", "photography", "nature"],
    lat: 11.3850, lng: 76.7400,
    popularity: 0.7, baseCrowd: 0.3,
    peakHours: [9, 10, 15, 16],
    bestTime: "Early morning when mist threads through the trees",
    culturalInfo: {
      myth: "Locals say if you stand silently at dawn, you can hear the forest whispering ancient songs.",
      festival: "Photography walks and nature camps during monsoon months.",
      history: "Planted by the British in the 19th century to remind them of European forests, it became one of Ooty's most iconic landmarks.",
    },
  },
];

// ===== STAYS =====
export const stays = [
  // Chennai
  { id: "taj-coromandel", name: "Taj Coromandel", city: "chennai", type: "hotel", description: "5-star luxury hotel in Nungambakkam with world-class dining and a rooftop pool.", priceRange: "₹8,000–₹25,000/night", rating: 4.7, amenities: ["Pool", "Spa", "Fine Dining", "WiFi", "Gym"], lat: 13.0600, lng: 80.2500, contact: "+91-44-6600-2827" },
  { id: "itc-grand-chola", name: "ITC Grand Chola", city: "chennai", type: "hotel", description: "Palatial hotel inspired by the Chola dynasty, featuring luxury suites and eight restaurants.", priceRange: "₹10,000–₹40,000/night", rating: 4.8, amenities: ["Pool", "Spa", "Multiple Restaurants", "Bar", "Business Center"], lat: 13.0090, lng: 80.2270, contact: "+91-44-2220-0000" },
  { id: "zostel-chennai", name: "Zostel Chennai", city: "chennai", type: "hostel", description: "Budget-friendly backpacker hostel near the beach with common kitchen and rooftop hangout.", priceRange: "₹500–₹1,500/night", rating: 4.2, amenities: ["WiFi", "Common Kitchen", "Locker", "Laundry"], lat: 13.0450, lng: 80.2700, contact: "+91-800-011-5511" },
  { id: "casa-cottage-chennai", name: "Casa Cottage", city: "chennai", type: "homestay", description: "Charming heritage homestay in Alwarpet with home-cooked South Indian breakfast.", priceRange: "₹2,500–₹4,000/night", rating: 4.5, amenities: ["Breakfast", "WiFi", "Garden", "Parking"], lat: 13.0350, lng: 80.2550, contact: "+91-98410-12345" },
  { id: "mgm-resort-chennai", name: "MGM Beach Resort", city: "chennai", type: "resort", description: "Beach resort on ECR with water sports, pool, and beachfront dining.", priceRange: "₹5,000–₹12,000/night", rating: 4.3, amenities: ["Beach Access", "Pool", "Water Sports", "Restaurant"], lat: 12.8700, lng: 80.2300, contact: "+91-44-2747-3000" },

  // Coimbatore
  { id: "vivanta-coimbatore", name: "Vivanta Coimbatore", city: "coimbatore", type: "hotel", description: "Premium hotel near the racecourse with modern rooms and a rooftop infinity pool.", priceRange: "₹6,000–₹15,000/night", rating: 4.5, amenities: ["Pool", "Spa", "Restaurant", "Bar", "Gym"], lat: 11.0200, lng: 76.9700, contact: "+91-422-661-3636" },
  { id: "isha-ashram-stay", name: "Isha Yoga Center Stay", city: "coimbatore", type: "homestay", description: "Simple ashram accommodation at the Isha Foundation with yoga programs and organic meals.", priceRange: "₹1,000–₹3,000/night", rating: 4.6, amenities: ["Yoga", "Meditation", "Organic Food", "Nature Walks"], lat: 11.0440, lng: 76.8400, contact: "+91-422-251-5345" },
  { id: "le-meridien-coimbatore", name: "Le Méridien Coimbatore", city: "coimbatore", type: "hotel", description: "International luxury hotel with elegant rooms and rooftop bar overlooking the city.", priceRange: "₹7,000–₹18,000/night", rating: 4.4, amenities: ["Pool", "Spa", "Restaurant", "Bar", "Business Center"], lat: 11.0180, lng: 76.9650, contact: "+91-422-225-3000" },
  { id: "hilltop-homestay-cbe", name: "Hilltop Heritage Homestay", city: "coimbatore", type: "homestay", description: "Cozy homestay on Marudhamalai foothills with stunning views and homemade Kongu meals.", priceRange: "₹1,500–₹3,500/night", rating: 4.3, amenities: ["Mountain Views", "Home Cooking", "WiFi", "Trekking"], lat: 11.0460, lng: 76.8900, contact: "+91-98430-56789" },

  // Madurai
  { id: "heritage-madurai", name: "Heritage Madurai", city: "madurai", type: "hotel", description: "A restored colonial club turned luxury hotel with sprawling gardens and a beautiful pool.", priceRange: "₹7,000–₹20,000/night", rating: 4.6, amenities: ["Pool", "Heritage Tours", "Spa", "Restaurant", "Garden"], lat: 9.9300, lng: 78.1050, contact: "+91-452-238-5455" },
  { id: "hotel-supreme-madurai", name: "Hotel Supreme", city: "madurai", type: "hotel", description: "Well-known mid-range hotel right opposite the Meenakshi Temple with rooftop dining.", priceRange: "₹2,500–₹5,000/night", rating: 4.1, amenities: ["Temple View", "Restaurant", "WiFi", "AC"], lat: 9.9200, lng: 78.1190, contact: "+91-452-234-3151" },
  { id: "tamil-house-madurai", name: "The Tamil House", city: "madurai", type: "homestay", description: "Authentic Tamil homestay in a 100-year-old house with courtyard, kolam, and traditional meals.", priceRange: "₹2,000–₹4,000/night", rating: 4.7, amenities: ["Traditional Meals", "Courtyard", "Cultural Activities", "WiFi"], lat: 9.9180, lng: 78.1160, contact: "+91-98430-11111" },
  { id: "poppy-hostel-madurai", name: "Poppy Hostel", city: "madurai", type: "hostel", description: "Vibrant backpacker hostel 5 minutes from Meenakshi Temple with temple-view terrace.", priceRange: "₹400–₹1,200/night", rating: 4.0, amenities: ["WiFi", "Rooftop", "Locker", "Tours"], lat: 9.9195, lng: 78.1200, contact: "+91-452-243-0000" },

  // Ooty
  { id: "savoy-ooty", name: "Savoy – IHCL SeleQtions", city: "ooty", type: "hotel", description: "A 19th-century heritage hotel with sprawling lawns, fireplaces, and old-world colonial charm.", priceRange: "₹8,000–₹22,000/night", rating: 4.6, amenities: ["Heritage", "Garden", "Restaurant", "Fireplace", "WiFi"], lat: 11.4100, lng: 76.6950, contact: "+91-423-225-5500" },
  { id: "king-cliff-ooty", name: "King Cliff Resort", city: "ooty", type: "resort", description: "Hilltop resort with panoramic views, bonfire nights, and nature trails through tea estates.", priceRange: "₹4,000–₹10,000/night", rating: 4.3, amenities: ["Mountain View", "Bonfire", "Tea Estate Walk", "Restaurant"], lat: 11.4050, lng: 76.7000, contact: "+91-423-244-3636" },
  { id: "toda-hut-stay", name: "Toda Hut Homestay", city: "ooty", type: "homestay", description: "Unique barrel-shaped hut accommodation inspired by Toda architecture with organic meals.", priceRange: "₹1,800–₹3,500/night", rating: 4.4, amenities: ["Cultural Experience", "Organic Food", "Nature", "WiFi"], lat: 11.4060, lng: 76.6890, contact: "+91-94430-22222" },
  { id: "zostel-ooty", name: "Zostel Ooty", city: "ooty", type: "hostel", description: "Backpacker hostel in a scenic location with bonfire nights, board games, and mountain views.", priceRange: "₹500–₹1,500/night", rating: 4.1, amenities: ["Bonfire", "Common Area", "WiFi", "Mountain View"], lat: 11.4120, lng: 76.7020, contact: "+91-800-011-5511" },
];

// ===== DINING =====
export const dining = [
  // Chennai
  { id: "murugan-idli-chennai", name: "Murugan Idli Shop", city: "chennai", type: "restaurant", cuisine: "South Indian", description: "Legendary chain known for the softest idlis and authentic Tamil filter coffee.", priceRange: "₹100–₹300", rating: 4.6, mustTry: ["Ghee Pongal", "Idli Set", "Filter Coffee"], lat: 13.0500, lng: 80.2550 },
  { id: "hotel-saravana-bhavan", name: "Saravana Bhavan", city: "chennai", type: "restaurant", cuisine: "South Indian Vegetarian", description: "World-famous vegetarian restaurant chain that started right here in Chennai.", priceRange: "₹150–₹500", rating: 4.5, mustTry: ["Masala Dosa", "Thali", "Rava Kesari"], lat: 13.0630, lng: 80.2670 },
  { id: "marina-beach-stalls", name: "Marina Beach Street Food", city: "chennai", type: "street-food", cuisine: "Street Food", description: "Iconic beach-side stalls serving sundal, bajji, corn, and rose milk.", priceRange: "₹20–₹100", rating: 4.3, mustTry: ["Sundal", "Bajji", "Rose Milk", "Corn"], lat: 13.0500, lng: 80.2820 },
  { id: "amethyst-cafe", name: "Amethyst Café", city: "chennai", type: "cafe", cuisine: "Continental & Indian", description: "Beautiful heritage café in Whites Road with garden seating and artisan pastries.", priceRange: "₹300–₹800", rating: 4.5, mustTry: ["Eggs Benedict", "Chocolate Cake", "Cold Brew"], lat: 13.0590, lng: 80.2580 },
  { id: "hot-chips-chennai", name: "Hot Chips", city: "chennai", type: "restaurant", cuisine: "Multi-cuisine", description: "Popular Chennai chain famous for crispy chips, chaats, and South Indian tiffin.", priceRange: "₹80–₹250", rating: 4.2, mustTry: ["Banana Chips", "Masala Chips", "Paneer Tikka"], lat: 13.0400, lng: 80.2600 },

  // Coimbatore
  { id: "annapoorna-cbe", name: "Sri Annapoorna", city: "coimbatore", type: "restaurant", cuisine: "South Indian", description: "Coimbatore's most iconic restaurant chain — filter coffee and ghee roast are legendary.", priceRange: "₹80–₹300", rating: 4.7, mustTry: ["Ghee Roast Dosa", "Filter Coffee", "Poori Set"], lat: 11.0170, lng: 76.9560 },
  { id: "kovai-biryani-cbe", name: "Kovai Biryani", city: "coimbatore", type: "restaurant", cuisine: "Kongu Non-Veg", description: "Authentic Kongu-style biryani with small onion salna — a regional speciality.", priceRange: "₹150–₹400", rating: 4.4, mustTry: ["Kongu Biryani", "Nattu Kozhi Curry", "Mutton Chukka"], lat: 11.0100, lng: 76.9650 },
  { id: "brew-house-cbe", name: "Brew House", city: "coimbatore", type: "cafe", cuisine: "Café & Bakery", description: "Trendy café with specialty coffee, artisan sandwiches, and weekend live music.", priceRange: "₹200–₹500", rating: 4.3, mustTry: ["Cappuccino", "Club Sandwich", "Brownie"], lat: 11.0250, lng: 76.9600 },
  { id: "kari-dosa-cbe", name: "Kari Dosai Kadai", city: "coimbatore", type: "street-food", cuisine: "Street Food", description: "Hole-in-the-wall serving the legendary Coimbatore kari dosa — meat-stuffed crepe.", priceRange: "₹60–₹150", rating: 4.5, mustTry: ["Kari Dosai", "Egg Dosa", "Mutton Soup"], lat: 11.0050, lng: 76.9700 },

  // Madurai
  { id: "murugan-idli-madurai", name: "Murugan Idli Shop", city: "madurai", type: "restaurant", cuisine: "South Indian", description: "The original branch — serving Madurai's finest idlis since 1962.", priceRange: "₹80–₹250", rating: 4.7, mustTry: ["Idli Set", "Pongal", "Jigarthanda"], lat: 9.9250, lng: 78.1200 },
  { id: "jigarthanda-stall", name: "Famous Jigarthanda", city: "madurai", type: "street-food", cuisine: "Beverages", description: "The legendary Madurai drink — a cold concoction of milk, almond gum, ice cream, and nannari.", priceRange: "₹50–₹120", rating: 4.8, mustTry: ["Special Jigarthanda", "Rose Milk"], lat: 9.9195, lng: 78.1195 },
  { id: "kumar-mess-madurai", name: "Kumar Mess", city: "madurai", type: "restaurant", cuisine: "Chettinad Non-Veg", description: "Legendary non-veg mess serving fiery Chettinad mutton curry and fish fry.", priceRange: "₹100–₹300", rating: 4.5, mustTry: ["Mutton Kuzhambu", "Meen Varuval", "Parotta"], lat: 9.9220, lng: 78.1180 },
  { id: "temple-view-cafe-madurai", name: "Meenakshi Temple View Café", city: "madurai", type: "cafe", cuisine: "Multi-cuisine", description: "Rooftop café with a stunning view of the Meenakshi Temple's gopurams.", priceRange: "₹200–₹500", rating: 4.3, mustTry: ["Masala Chai", "Parotta Kurma", "Sunset View"], lat: 9.9200, lng: 78.1195 },
  { id: "simmakkal-street-food", name: "Simmakkal Street Food Lane", city: "madurai", type: "street-food", cuisine: "Street Food", description: "A narrow lane exploding with flavors — vada, bonda, and fresh juice stalls.", priceRange: "₹20–₹100", rating: 4.4, mustTry: ["Paruthi Paal", "Bonda", "Vada", "Sugarcane Juice"], lat: 9.9210, lng: 78.1185 },

  // Ooty
  { id: "earl-grey-ooty", name: "Earl's Secret", city: "ooty", type: "cafe", cuisine: "Continental & Nilgiri", description: "Charming café in a colonial bungalow serving Nilgiri tea, scones, and wood-fired pizzas.", priceRange: "₹300–₹700", rating: 4.5, mustTry: ["Nilgiri Tea", "Scones", "Wood-fired Pizza"], lat: 11.4100, lng: 76.6960 },
  { id: "sidewalk-cafe-ooty", name: "Sidewalk Café", city: "ooty", type: "cafe", cuisine: "Multi-cuisine", description: "Cozy hillside café with hot chocolate, pancakes, and mountain views.", priceRange: "₹200–₹500", rating: 4.4, mustTry: ["Hot Chocolate", "Pancakes", "Mushroom Soup"], lat: 11.4080, lng: 76.6980 },
  { id: "choco-factory-ooty", name: "King Star Chocolate Factory", city: "ooty", type: "bakery", cuisine: "Chocolates & Sweets", description: "Famous homemade chocolates — dark, fruit & nut, and Nilgiri tea-infused varieties.", priceRange: "₹100–₹500", rating: 4.3, mustTry: ["Dark Chocolate", "Fruit & Nut Bar", "Tea Chocolate"], lat: 11.4120, lng: 76.7000 },
  { id: "quality-restaurant-ooty", name: "Quality Restaurant", city: "ooty", type: "restaurant", cuisine: "North & South Indian", description: "One of Ooty's oldest restaurants serving hearty meals perfect for the cold weather.", priceRange: "₹150–₹400", rating: 4.2, mustTry: ["Chicken Biryani", "Naan & Curry", "Hot Soup"], lat: 11.4090, lng: 76.6940 },
];

// ===== EVENTS (sample data — in production, fetched from APIs) =====
export const events = [
  // Chennai
  { id: "evt-1", title: "Margazhi Music Festival", city: "chennai", type: "concert", description: "Annual Carnatic music festival featuring hundreds of concerts across sabhas.", venue: "Music Academy, T Nagar", date: "2026-12-15", time: "6:00 PM", price: "₹200–₹2,000", link: "#" },
  { id: "evt-2", title: "Praveen Kumar Stand-Up Special", city: "chennai", type: "standup", description: "Tamil & English stand-up comedy show by YouTube sensation Praveen Kumar.", venue: "Sir Mutha Venkatasubba Rao Concert Hall", date: "2026-05-10", time: "7:30 PM", price: "₹499–₹1,499", link: "#" },
  { id: "evt-3", title: "Chennai Photo Biennale", city: "chennai", type: "exhibition", description: "International photography exhibition across multiple venues in the city.", venue: "Multiple Venues, George Town", date: "2026-05-01", time: "10:00 AM", price: "Free", link: "#" },
  { id: "evt-4", title: "Bharatanatyam at Kalakshetra", city: "chennai", type: "theatre", description: "Classical dance performance by Kalakshetra Foundation students.", venue: "Kalakshetra Foundation, Thiruvanmiyur", date: "2026-05-20", time: "6:30 PM", price: "₹100–₹500", link: "#" },
  { id: "evt-5", title: "Chennai Comedy Club Night", city: "chennai", type: "standup", description: "Weekly open-mic comedy night with emerging Tamil comedians.", venue: "The Comedy Factory, Alwarpet", date: "2026-05-03", time: "8:00 PM", price: "₹299", link: "#" },

  // Coimbatore
  { id: "evt-6", title: "Sounds of Isha Live", city: "coimbatore", type: "concert", description: "Live spiritual music concert at Isha Yoga Center.", venue: "Isha Yoga Center, Velliangiri Foothills", date: "2026-05-15", time: "7:00 PM", price: "Free", link: "#" },
  { id: "evt-7", title: "Coimbatore Comedy Fest", city: "coimbatore", type: "standup", description: "Multi-comedian stand-up show featuring Tamil Nadu's funniest acts.", venue: "Brookefields Mall Auditorium", date: "2026-05-22", time: "7:00 PM", price: "₹399–₹999", link: "#" },
  { id: "evt-8", title: "Kongu Pottery Workshop", city: "coimbatore", type: "workshop", description: "Hands-on traditional Kongu pottery-making workshop with local artisans.", venue: "GeDee Cultural Center", date: "2026-05-18", time: "10:00 AM", price: "₹500", link: "#" },

  // Madurai
  { id: "evt-9", title: "Chithirai Thiruvizha 2026", city: "madurai", type: "festival", description: "The grand 10-day celestial wedding festival of Meenakshi and Sundareshwarar.", venue: "Meenakshi Amman Temple", date: "2026-04-25", time: "All Day", price: "Free", link: "#" },
  { id: "evt-10", title: "Madurai Comedy Night", city: "madurai", type: "standup", description: "Tamil stand-up comedy featuring local and touring comedians.", venue: "Hotel Heritage, Madurai", date: "2026-05-08", time: "7:30 PM", price: "₹299–₹599", link: "#" },
  { id: "evt-11", title: "Jallikattu Season Opener", city: "madurai", type: "festival", description: "The legendary bull-taming sport of Tamil Nadu returns for the Pongal season.", venue: "Alanganallur Arena", date: "2026-01-15", time: "8:00 AM", price: "Free", link: "#" },
  { id: "evt-12", title: "Temple Heritage Walk", city: "madurai", type: "workshop", description: "Guided heritage walk through Madurai's ancient temple corridors and bazaars.", venue: "Starting at Meenakshi Temple East Gate", date: "2026-05-12", time: "6:00 AM", price: "₹200", link: "#" },

  // Ooty
  { id: "evt-13", title: "Ooty Flower Show 2026", city: "ooty", type: "festival", description: "The spectacular annual flower show with over 5 lakh blooms on display.", venue: "Botanical Garden", date: "2026-05-20", time: "9:00 AM", price: "₹50", link: "#" },
  { id: "evt-14", title: "Nilgiri Tea Festival", city: "ooty", type: "festival", description: "Celebrate the Nilgiri flush with tea tastings, factory tours, and cultural programs.", venue: "Various Tea Estates", date: "2026-12-10", time: "10:00 AM", price: "₹300", link: "#" },
  { id: "evt-15", title: "Mountain Music Weekend", city: "ooty", type: "concert", description: "Acoustic music festival featuring indie artists performing in the misty mountains.", venue: "King Cliff Resort Grounds", date: "2026-05-30", time: "4:00 PM", price: "₹500–₹1,500", link: "#" },
];

// ===== HELPER FUNCTIONS =====

